# Elixir CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/elixir:1.10.1-node-browsers-legacy
        environment:
          MIX_ENV: test
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run:
          name: Starting PhantomJS
          command: phantomjs -w --webdriver-loglevel=ERROR
          background: true
      - run: mix deps.get
      - run: mix compile --warnings-as-errors
      - run: mix credo
      - run: mix test
