# Elixir CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/elixir:1.10.1-node-browsers-legacy
        environment:
          MIX_ENV: test
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependency-cache-{{ checksum "mix.lock" }}
            - v1-dependency-cache
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run:
          name: Starting PhantomJS
          command: phantomjs -w --webdriver-loglevel=ERROR
          background: true
      - run: mix deps.get
      - run: mix compile --warnings-as-errors
      - restore_cache:
          keys:
            - v2-plt-cache-{{ checksum "mix.lock" }}
            - v2-plt-cache
      - run: mix dialyzer --plt
      - run: mix dialyzer --list-unused-filters
      - save_cache:
          key: v2-plt-cache-{{ checksum "mix.lock" }}
          paths:
            - _build
            - priv/plts
            - ~/.mix
      - run: mix credo
      - run: mix test
      - run: mix coveralls.json
      - run: bash <(curl -s https://codecov.io/bash) -t "$CODECOV_KEY"
      - save_cache:
          key: v1-dependency-cache-{{ checksum "mix.lock" }}
          paths:
            - deps
            - _build
            - ~/.mix
